//
//  DeveloperPreview.swift
//  AirbnbClone
//
//  Created by Zoltan Vegh on 11/08/2025.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Zoltan Vegh", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 34.0549, longitude: -118.2426, imageUrls: ["listing-2", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Los Angeles", state: "California", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Abdullah Mohammed", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 26.7850, longitude: -80.1936, imageUrls: ["listing-5", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Mohammed Abdul", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 27.7850, longitude: -80.1936, imageUrls: ["listing-6", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "James Cook", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 28.7850, longitude: -80.1936, imageUrls: ["listing-7", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Los Angeles", state: "California", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Wayne Rooney", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 29.7850, longitude: -80.1936, imageUrls: ["listing-8", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Los Angeles", state: "California", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Rodney McKay", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 30.7850, longitude: -80.1936, imageUrls: ["listing-4", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "John Shephard", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 31.7850, longitude: -80.1936, imageUrls: ["listing-5", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Samantha Carter", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 32.7850, longitude: -80.1936, imageUrls: ["listing-6", "listing-1", "listing-3", " listing-4"], address: "124 Main Street", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Eniko Torok", ownerImageUrl: "male-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 33.7850, longitude: -80.1936, imageUrls: ["listing-1", "listing-2", "listing-3", " listing-4"], address: "124 Main Street", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superHost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
    ]
}
